### PR TITLE
Added a few dependencies. Completed 00, 01, and 02.

### PR DESCRIPTION
**Pull request by catslanderer**

### CODE REVIEW

**Review by wandadotdev — COMMENTED** [review]
Looking good so far, Christopher!

**Review by wandadotdev — COMMENTED** [review]
I saw that you were chatting with Jubilee yesterday and she brought up try/except. I've never used it before myself and it's pretty awesome you made it work.

**Comment by catslanderer** [comment]
> I saw that you were chatting with Jubilee yesterday and she brought up try/except. I've never used it before myself and it's pretty awesome you made it work.

Oh that's interesting - I found try/except while searching for 'how to end a python script'. I was looking for the sys.exit() command, but found more than I was looking for.

**Comment by wandadotdev** [comment]
> > I saw that you were chatting with Jubilee yesterday and she brought up try/except. I've never used it before myself and it's pretty awesome you made it work.
> 
> Oh that's interesting - I found try/except while searching for 'how to end a python script'. I was looking for the sys.exit() command, but found more than I was looking for.

Maybe it wasn't you. LOL, I'm sorry!

**Pull request merged**
